include ../../common.mk

EXTRA_LIBVPATH+=$(PRODUCT_ROOT)/BulletCollision/arm/a.le.v7 \
    $(PRODUCT_ROOT)/BulletDynamics/arm/a.le.v7 \
    $(PRODUCT_ROOT)/LinearMath/arm/a.le.v7 \
    $(PRODUCT_ROOT)/OpenGLSupport/arm/a.le.v7 \
    $(PRODUCT_ROOT)/BulletFileLoader/arm/a.le.v7 \
    $(PRODUCT_ROOT)/BulletWorldImporter/arm/a.le.v7

LIBS+=BulletWorldImporter BulletFileLoader OpenGLSupport BulletDynamics BulletCollision LinearMath