include ../../common.mk

EXTRA_LIBVPATH+=$(PRODUCT_ROOT)/BulletCollision/arm/a.le.v7.g \
    $(PRODUCT_ROOT)/BulletDynamics/arm/a.le.v7.g \
    $(PRODUCT_ROOT)/LinearMath/arm/a.le.v7.g \
    $(PRODUCT_ROOT)/OpenGLSupport/arm/a.le.v7.g \

LIBS+=OpenGLSupport BulletDynamics BulletCollision LinearMath