include ../../common.mk

EXTRA_LIBVPATH+=$(PRODUCT_ROOT)/BulletCollision/x86/a \
    $(PRODUCT_ROOT)/BulletDynamics/x86/a \
    $(PRODUCT_ROOT)/BulletSoftBody/x86/a \
    $(PRODUCT_ROOT)/LinearMath/x86/a \
    $(PRODUCT_ROOT)/OpenGLSupport/x86/a \

LIBS+=OpenGLSupport BulletSoftBody BulletDynamics BulletCollision LinearMath