include ../../common.mk

EXTRA_LIBVPATH+=$(PRODUCT_ROOT)/BulletCollision/x86/a.g \
    $(PRODUCT_ROOT)/BulletDynamics/x86/a.g \
    $(PRODUCT_ROOT)/LinearMath/x86/a.g \
    $(PRODUCT_ROOT)/OpenGLSupport/x86/a.g \
    $(PRODUCT_ROOT)/ConvexDecomposition/x86/a.g \
    $(PRODUCT_ROOT)/HACD/x86/a.g \

LIBS+=HACD ConvexDecomposition OpenGLSupport BulletDynamics BulletCollision LinearMath