all: libs demos

libs:
	cd BulletCollision && make
	cd BulletDynamics && make
	cd BulletSoftBody && make
	cd LinearMath && make
	cd HACD && make
	cd ConvexDecomposition && make
	cd BulletFileLoader && make
	cd BulletWorldImporter && make
    
demos:
	cd OpenGLSupport && make
	cd BasicDemo && make
	cd Box2dDemo && make
	cd BspDemo && make
	cd CcdPhysicsDemo && make
	cd CollisionDemo && make
	cd CollisionInterfaceDemo && make
	cd ConcaveConvexcastDemo && make
	cd ConcaveDemo && make
	cd ConcaveRaycastDemo && make
	cd ConstraintDemo && make
	cd ContinuousConvexCollision && make
	cd ConvexDecompositionDemo && make
	cd ConvexHullDistance && make
	cd DynamicControlDemo && make
	cd EPAPenDepthDemo && make
	cd ForkLiftDemo && make
	cd FractureDemo && make
	cd GenericJointDemo && make
	cd GimpactTestDemo && make
	cd GjkConvexCastDemo && make
	cd HelloWorld && make
	cd InternalEdgeDemo && make
	cd MovingConcaveDemo && make
	cd MultiMaterialDemo && make
	cd RagdollDemo && make
	cd Raytracer && make
	cd SerializeDemo && make
	cd SimplexDemo && make
	cd SliderConstraintDemo && make
	cd SoftDemo && make
	cd TerrainDemo && make
	cd UserCollisionAlgorithm && make
	cd VehicleDemo && make
    
clean:
	cd BulletCollision && make clean
	cd BulletDynamics && make clean
	cd BulletSoftBody && make clean
	cd LinearMath && make clean
	cd HACD && make clean
	cd ConvexDecomposition && make clean
	cd BulletFileLoader && make clean
	cd BulletWorldImporter && make clean
	cd OpenGLSupport && make clean
	cd BasicDemo && make clean
	cd Box2dDemo && make clean
	cd BspDemo && make clean
	cd CcdPhysicsDemo && make clean
	cd CollisionDemo && make clean
	cd CollisionInterfaceDemo && make clean
	cd ConcaveConvexcastDemo && make clean
	cd ConcaveDemo && make clean
	cd ConcaveRaycastDemo && make clean
	cd ConstraintDemo && make clean
	cd ContinuousConvexCollision && make clean
	cd ConvexDecompositionDemo && make clean
	cd ConvexHullDistance && make clean
	cd DynamicControlDemo && make clean
	cd EPAPenDepthDemo && make clean
	cd ForkLiftDemo && make clean
	cd FractureDemo && make clean
	cd GenericJointDemo && make clean
	cd GimpactTestDemo && make clean
	cd GjkConvexCastDemo && make clean
	cd HelloWorld && make clean
	cd InternalEdgeDemo && make clean
	cd MovingConcaveDemo && make clean
	cd MultiMaterialDemo && make clean
	cd RagdollDemo && make clean
	cd Raytracer && make clean
	cd SerializeDemo && make clean
	cd SimplexDemo && make clean
	cd SliderConstraintDemo && make clean
	cd SoftDemo && make clean
	cd TerrainDemo && make clean
	cd UserCollisionAlgorithm && make clean
	cd VehicleDemo && make clean