include ../../common.mk

EXTRA_LIBVPATH+=$(PRODUCT_ROOT)/BulletCollision/x86/a.g \
    $(PRODUCT_ROOT)/BulletDynamics/x86/a.g \
    $(PRODUCT_ROOT)/LinearMath/x86/a.g \
    $(PRODUCT_ROOT)/OpenGLSupport/x86/a.g \
    $(PRODUCT_ROOT)/BulletFileLoader/x86/a.g \
    $(PRODUCT_ROOT)/BulletWorldImporter/x86/a.g

LIBS+=BulletWorldImporter BulletFileLoader OpenGLSupport BulletDynamics BulletCollision LinearMath